### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by dec0dOS**
Fixed typo. "styleki" to "stylekit"

### CODE REVIEW

**Comment by atmoio** [comment]
Thanks! Can you also build via `npm run build` and include those files?

**Comment by dec0dOS** [comment]
Done! 👍

**Review by atmoio — APPROVED** [review]

**Comment by dec0dOS** [comment]
Could you bump the npm version as well and publish it?

**Comment by atmoio** [comment]
Done 👍

**Pull request merged**
